dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.3.2
    - witnet/witnet-solidity-bridge@0.5.7
compiler:
    evm_version: london
    solc:
        version: 0.8.7
        remappings:
            - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.3.2'
            - '@witnet/witnet-solidity-bridge=witnet/witnet-solidity-bridge@0.5.7'
dotenv: .env
wallets:
    from_key_goerli: ${PRIVATE_KEY_GOERLI}
    from_key_ethereum: ${PRIVATE_KEY_ETHEREUM}
